void blackLineDetect(int shade);
void blackLineDetectReverse(int shade);
void driveDistance(int distance);
void lineFollow(int shade);
void lineFollowSquareUp(int shade);
void lineFollowSquareReverse(int shade);
void squareUp();
void squareUpReverse();
void servoPosition(int servo, int position);
void timeServo(int port, int endAngle, float time);
void turnDegrees(int degrees);
void driveDistanceSpeed(int distance, int LWheelspeed, int RWheelspeed);
